name: auto-update

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "* * * * *"
    # - cron: "*/5 * * * *"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:

    - name: check out this repo
      uses: actions/checkout@v2
      with:
        path: nk
        fetch-depth: 0

    - name: check out nkantar.com repo
      uses: actions/checkout@v2
      with:
        repository: nkantar/nkantar.com
        path: nkc
        token: ${{ secrets.GH_PAT }}

    - name: configure git
      run: |
        git config --global user.email "nik@nkantar.com"
        git config --global user.name "Nik Kantar"
        git config --global github.user "nkantar"
    
    - name: update README.md from about.md
      run: |
        cp nkc/input/about/index.md nk/README.md
        tail -n +5 nk/README.md > nk/README.md

    - name: add, commit, push
      run: |
        cd nk
        git add README.md
        git commit -m "Updating" --allow-empty
        git push origin master
