name: auto-update

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "*/5 * * * *"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:

    - name: check out this repo
      uses: actions/checkout@v2
      with:
        path: nk
        fetch-depth: 0

    - name: check out nkantar.com repo
      uses: actions/checkout@v2
      with:
        repository: nkantar/nkantar.com
        path: nkc
        token: ${{ secrets.GH_PAT }}

    - name: configure git
      run: |
        git config --global user.email "nik@nkantar.com"
        git config --global user.name "Nik Kantar"
        git config --global github.user "nkantar"
    
    - name: update README.md from about.md
      run: |
        cp nkc/input/about/index.md nk/README.md
        sed -i "1,3d" nk/README.md

    - name: check if there are changes
      env:
        GDIFF: empty
      run: |
        cd nk
        export GDIFF=`git diff`

    - name: add, commit, push
      if: ${{ env.GDIFF == 'empty' }}
      run: |
        git add README.md
        git commit -m "Updating" --allow-empty
        git push origin master
